### ISSUE TITLE
Can help with ci/cd pipeline setup

### ISSUE THREAD

**Issue by mehul1011** [szymonpoltorak/Social-App#18]
Hi @szymonpoltorak, 
If you are looking for collaboration let me know, we can deploy the app and take it to the next level, basically making it a social media app based with an open-ended codebase for users to view.

**Comment by szymonpoltorak** [comment]
Hi @mehul1011,
Thanks for your proposal but unfortunately I have to decline your offer due to the fact it is an individual project for one of my academic courses so I have to make it alone. I do really appreciate your offer anyway ^^!

**Comment by mehul1011** [comment]
> Hi @mehul1011,
> Thanks for your proposal but unfortunately I have to decline your offer due to the fact it is an individual project for one of my academic courses so I have to make it alone. I do really appreciate your offer anyway ^^!

That's cool (;
